### ISSUE TITLE
Not launching - Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by nginYthough** [ripmeapp2/ripme#101]
* Ripme version: ripme-2.1.2-3-ea90b172
* Java version:
  - java version "11.0.16" 2022-07-19 LTS
  - java version "17.0.1" 2021-10-19 LTS
  - java version "18.0.2" 2022-07-19

* Operating system: Windows 10 21H2 (Build 19044.1826)

* Exact URL you were trying to rip when the problem occurred: None
* Please include any additional information about how to reproduce the problem: Try to launch ripme via command prompt to get log output.

## Expected Behavior
ripme launches.

## Actual Behavior
ripme does not launch.

```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.rarchives.ripme.App.main(App.java:62)
Caused by: java.util.MissingResourceException: Can't find bundle for base name LabelsBundle, locale en_EN
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1066)
        at com.rarchives.ripme.utils.Utils.getResourceBundle(Utils.java:733)
        at com.rarchives.ripme.utils.Utils.<clinit>(Utils.java:104)
        ... 1 more
```

**Comment by soloturn** [comment]
this does not seem to be a general problem? you have some config folder? if you have details please reopen.
