### ISSUE TITLE
Vsco ripper broken?

### ISSUE THREAD

**Issue by dusteroad** [ripmeapp2/ripme#104]
Ripme version: 2.1.2-3-ea90b172

Java version: java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

Operating system: Microsoft Windows [Version 10.0.19044.1826]

Exact URL you were trying to rip when the problem occurred: https://vsco.co/[ANY_USER]/gallery

## Expected Behavior

Rip user images.

## Actual Behavior

Error: Cookie value must not be null

Log - Cookie value must not be null

**Comment by RuneDemomn** [comment]
Same issue

**Comment by holysoles** [comment]
Notable that ripping a single image still works correctly, which means `vscoImageToURL` should still be working correctly.
- https://vsco.co/<username>/media/<media file hash>

Full exception details:
```18:26:55.917 [main] ERROR com.rarchives.ripme.App - [!] Error while ripping URL https://vsco.co/<username>/gallery
java.lang.IllegalArgumentException: Cookie value must not be null
        at org.jsoup.helper.Validate.notNull(Validate.java:28) ~[jsoup-1.14.3.jar:?]
        at org.jsoup.helper.HttpConnection$Base.cookie(HttpConnection.java:609) ~[jsoup-1.14.3.jar:?]
        at org.jsoup.helper.HttpConnection$Request.cookie(HttpConnection.java:630) ~[jsoup-1.14.3.jar:?]
        at org.jsoup.helper.HttpConnection.cookies(HttpConnection.java:329) ~[jsoup-1.14.3.jar:?]
        at com.rarchives.ripme.utils.Http.cookies(Http.java:145) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.VscoRipper.getSiteID(VscoRipper.java:148) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.VscoRipper.getURLsFromPage(VscoRipper.java:85) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:127) ~[main/:?]
        at com.rarchives.ripme.App.rip(App.java:100) ~[main/:?]
        at com.rarchives.ripme.App.ripURL(App.java:293) [main/:?]
        at com.rarchives.ripme.App.handleArguments(App.java:276) [main/:?]
        at com.rarchives.ripme.App.main(App.java:75) [main/:?]```

**Comment by holysoles** [comment]
`tkn` is null at [line 149](https://github.com/ripmeapp2/ripme/blob/main/src/main/java/com/rarchives/ripme/ripper/rippers/VscoRipper.java#L149)

That means `getUserTkn()` is returning a null value there is a catch block for `IOException`s during the web request, so vsco probably changed how this is being returned
