### ISSUE TITLE
Updater finds ripme-2.1.8-1-f5153de8.jar but it is not there

### ISSUE THREAD

**Issue by colemar** [ripmeapp2/ripme#170]
```
C:\Users\colem\AppData\Local\RipMe>"c:\Program Files\Java\jdk-21.0.1\bin\java.exe" -jar ripme-2.1.8.jar
12:41:59.465 [main] DEBUG com.rarchives.ripme.utils.Utils - Key select.save.dir in en_US is: Select Save Directory
12:41:59.474 [main] DEBUG com.rarchives.ripme.utils.Utils - Key loading.history.from.configuration in en_US is: Loading history from configuration
12:41:59.474 [main] INFO  com.rarchives.ripme.ui.MainWindow - Loading history from configuration
12:41:59.551 [Thread-1] DEBUG com.rarchives.ripme.ui.UpdateUtils - Retrieving https://raw.githubusercontent.com/ripmeapp2/ripme/main/ripme.json
12:41:59.718 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.hide in en_US is: Hide
12:42:00.289 [Thread-1] DEBUG com.rarchives.ripme.ui.UpdateUtils - oldVersion 2.1.8 < latestVersion 2.1.8-1-f5153de8
12:42:00.289 [Thread-1] INFO  com.rarchives.ripme.ui.UpdateUtils - Found newer version: 2.1.8-1-f5153de8
12:42:00.654 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.show in en_US is: Show
12:42:54.098 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.hide in en_US is: Hide
12:42:54.105 [Thread-1] INFO  com.rarchives.ripme.ui.UpdateUtils - New version found, downloading https://github.com/ripmeapp2/ripme/releases/download/2.1.8/ripme-2.1.8-1-f5153de8.jar
12:42:54.436 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.show in en_US is: Show
12:45:22.293 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.hide in en_US is: Hide
12:45:22.298 [Thread-1] ERROR com.rarchives.ripme.ui.UpdateUtils - Error while updating:
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=[https://github.com/ripmeapp2/ripme/releases/download/2.1.8/ripme-2.1.8-1-f5153de8.jar]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912) ~[ripme-2.1.8.jar:2.1.8]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851) ~[ripme-2.1.8.jar:2.1.8]
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.UpdateUtils.downloadJarAndLaunch(UpdateUtils.java:256) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.UpdateUtils.updateProgramGUI(UpdateUtils.java:161) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.MainWindow.lambda$upgradeProgram$1(MainWindow.java:187) ~[ripme-2.1.8.jar:2.1.8]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
12:45:25.898 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.show in en_US is: Show
```

**Comment by soloturn** [comment]
newer releases are out.

**Comment by colemar** [comment]
![image](https://github.com/user-attachments/assets/5c1f6b6b-6d3c-4c9e-b4f9-4e4f397ddefe)
```
11:48:05.261 [Thread-2] DEBUG com.rarchives.ripme.ui.UpdateUtils - Retrieving https://raw.githubusercontent.com/ripmeapp2/ripme/main/ripme.json
11:48:05.973 [Thread-2] DEBUG com.rarchives.ripme.ui.UpdateUtils - oldVersion 2.1.8 < latestVersion 2.1.11-20-ca96ce88
11:48:05.974 [Thread-2] INFO  com.rarchives.ripme.ui.UpdateUtils - Found newer version: 2.1.11-20-ca96ce88
11:48:06.352 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.show in  is: Show
11:48:14.575 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.hide in  is: Hide
11:48:14.583 [Thread-2] INFO  com.rarchives.ripme.ui.UpdateUtils - New version found, downloading https://github.com/ripmeapp2/ripme/releases/download/2.1.11/ripme-2.1.11-20-ca96ce88.jar
11:48:14.899 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.show in  is: Show
11:49:45.718 [AWT-EventQueue-0] DEBUG com.rarchives.ripme.utils.Utils - Key tray.hide in  is: Hide
11:49:45.720 [Thread-2] ERROR com.rarchives.ripme.ui.UpdateUtils - Error while updating:
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=[https://github.com/ripmeapp2/ripme/releases/download/2.1.11/ripme-2.1.11-20-ca96ce88.jar]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912) ~[ripme-2.1.8.jar:2.1.8]
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851) ~[ripme-2.1.8.jar:2.1.8]
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.UpdateUtils.downloadJarAndLaunch(UpdateUtils.java:256) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.UpdateUtils.updateProgramGUI(UpdateUtils.java:161) ~[ripme-2.1.8.jar:2.1.8]
        at com.rarchives.ripme.ui.MainWindow.lambda$setupHandlers$14(MainWindow.java:936) ~[ripme-2.1.8.jar:2.1.8]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```

Will try manual update.

**Comment by soloturn** [comment]
now fixed with release-2.1.12
