### ISSUE TITLE
RedGIFs ripper broken

### ISSUE THREAD

**Issue by SilentModem** [ripmeapp2/ripme#215]
* Ripme version: 2.1.11
* Java version:  23.0.1
* Operating system:  macOS 15.1

* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/busty_asians (NSFW)
* Please include any additional information about how to reproduce the problem: 

Rip any(?) subreddit with redgifs, and with logs enabled. While RedGIFs links are retrieved, RedGIFs are not downloaded, and do not appear in the application log window with any associated error, only in the log file.

The RedGIFs URL is valid (https://www.redgifs.com/watch/cruelmediumspringgreenkentrosaurus, NSFW), but the video file link parsed from it (https://api.redgifs.com/v2/gifs/cruelmediumspringgreenkentrosaurus) returns 401 Unauthorized  in the log. At that link: {"error":{"code":"AuthorizationHeaderMissing","description":"Authorization header is missing."}}

I was able to access the RedGIFs file at https://files.redgifs.com/CruelMediumspringgreenKentrosaurus.mp4 (NSFW)

## Expected Behavior

Retrieve and download all redgifs

## Actual Behavior

No RedGIFs are downloaded.

A log snippet:

```
Checking https://www.redgifs.com/watch/cruelmediumspringgreenkentrosaurus
Fetching redgifs page https://www.redgifs.com/watch/cruelmediumspringgreenkentrosaurus
Retrieving https://www.redgifs.com/watch/cruelmediumspringgreenkentrosaurus
Trying to load cookies from config for api.redgifs.com
Trying to load cookies from config for redgifs.com
Exception while retrieving redgifs page:
java.io.IOException: Failed to load https://api.redgifs.com/v2/gifs/cruelmediumspringgreenkentrosaurus: Status Code 401. You might be able to circumvent this error by setting cookies for this domain
	at com.rarchives.ripme.utils.Http.response(Http.java:215) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.utils.Http.getJSON(Http.java:186) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.rippers.RedgifsRipper.getVideoURL(RedgifsRipper.java:270) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:62) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:412) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:230) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:122) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:93) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:637) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=401, URL=[https://api.redgifs.com/v2/gifs/cruelmediumspringgreenkentrosaurus]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345) ~[ripme_.jar:2.1.11-20-ca96ce88]
	at com.rarchives.ripme.utils.Http.response(Http.java:202) ~[ripme_.jar:2.1.11-20-ca96ce88]
	... 9 more
```

**Comment by SilentModem** [comment]
Oops, did not see the "Incase of redgif 401 errors, please restart the app to refresh the auth token" in the log. RedGIFs ripper does still work after reopening app.
