### ISSUE TITLE
Stopping while downloading reddit.

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#56]
Ripme 2.0.2

I had to go back to ripme-2.0.1-12-30f4cf3a as the new version stop downloading after a while.  I haven't had time to look into it I just wanted to get a post out for people experiencing similar.  

It always seems to stop way more often. I have to click stop then rip to get it started again. 

There was an old bug where it did this once in a while due to i think file name and path length issues.  Not sure what is causing this I will investigate later.

Windows 10 v20H2 builc 19042.1415

**Comment by madhatr** [comment]
Here is the an error that popped up resulting in a halt on downloading.  The stop button even greyed out this time, and hitting rip did nothing.  This is very similar behavior in versions way back.

User  https://www.reddit.com/user/JSU23

> Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Error while loading https://www.reddit.com/user/JSU23.json?after=t1_hbj6s5f
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_311]
	at java.net.SocketInputStream.socketRead(Unknown Source) ~[?:1.8.0_311]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl.access$300(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.fill(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_311]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_311]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:867) ~[ripme-2.0.2.jar:2.0.2]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829) ~[ripme-2.0.2.jar:2.0.2]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.utils.Http.response(Http.java:191) [ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:166) [ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:99) [ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:88) [ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:624) [ripme-2.0.2.jar:2.0.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Got exception while running ripper:
java.io.IOException: Failed to load https://www.reddit.com/user/JSU23.json?after=t1_hbj6s5f after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:212) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:166) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:99) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:88) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:624) [ripme-2.0.2.jar:2.0.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_311]
	at java.net.SocketInputStream.socketRead(Unknown Source) ~[?:1.8.0_311]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl.access$300(Unknown Source) ~[?:1.8.0_311]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.fill(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_311]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_311]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_311]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_311]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:867) ~[ripme-2.0.2.jar:2.0.2]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829) ~[ripme-2.0.2.jar:2.0.2]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366) ~[ripme-2.0.2.jar:2.0.2]
	at com.rarchives.ripme.utils.Http.response(Http.java:191) ~[ripme-2.0.2.jar:2.0.2]
	... 5 more
Waiting for threads to finish
Getting key tray.hide in en_US value Hide
Getting key tray.hide in en_US value Hide

**Comment by soloturn** [comment]
on linux one could try to find files longer than e.g. 150 characters:
```
> find /tmp/rips/ -regextype posix-extended -regex '.{255,}'
```
in windows 10 you might want to opt in to have longer filenames like so:
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

but, tbh,, a timeoutexception means your program waits for an answer from the server, which does not come. see here @borderline323 changes :
https://github.com/RipMeApp/ripme/compare/f1db4300c2a8f81737bdc17de7ba7ecabf1cb5b2...ripmeapp2:9ca49a2fc653a44652f8b7ca430b3c0156a28c62

**Comment by madhatr** [comment]
I am pretty sure the  timeout was coincidence.  It has to do with the "Waiting for threads to finish" as I believe they are all stuck.
Here is the last few lines of todays log before closing the program as it is stuck.

> Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking https://www.pornhub.com/view_video.php?viewkey=ph5fc08b3dce698
[!] Unable to rip URL: https://www.pornhub.com/view_video.php?viewkey=ph5fc08b3dce698
Checking https://www.pornhub.com/view_video.php?viewkey=ph5fc08b3dce698
[!] Unable to rip URL: https://www.pornhub.com/view_video.php?viewkey=ph5fc08b3dce698
Checking https://www.pornhub.com/model/alberta-couple
[!] Unable to rip URL: https://www.pornhub.com/model/alberta-couple
Checking https://www.pornhub.com/model/alberta-couple
[!] Unable to rip URL: https://www.pornhub.com/model/alberta-couple
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Waiting for threads to finish
Getting key tray.hide in en_US value Hide
Getting key tray.hide in en_US value Hide
Getting key tray.show in en_US value Show

So once the program is stuck while downloading.  I am unable to hit the stop button as it is greyed out. (sometimes I can hit stop and rip to restart) Also hitting the RIP button to does nothing.  The only way to fix is to close the program and open it again and it resumes the queue.

Side note, there was over 800,000 entries of "Caught and recovered from IllegalStateException: cannot open system clipboard".  Line 79820 to 885062

**Comment by madhatr** [comment]
Another one, this time I checked which user it was u/over_doze  I hit the stop button this time because it was available.

> Waiting for threads to finish
Getting key tray.hide in en_US value Hide
Getting key tray.hide in en_US value Hide
Getting key download.interrupted in en_US value Download interrupted
Getting key tray.show in en_US value Show

**Comment by madhatr** [comment]
So I did as you suggested and enabled longer file names.  Which I don't think I should have to do. The program should prevent the writing of illegal lengths on given OS.   If that is even my issue here.  I don't think longnames works because after reading the article it looks like longnames only work when you call specific windows writing functions.

Anyway it happened again.  Same log, waiting for threads.
`[!] Unable to rip URL: http://OnlyFans.com/Jade.Love)**
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking http://OnlyFans.com/Jade.Love)**
[!] Unable to rip URL: http://OnlyFans.com/Jade.Love)**
Waiting for threads to finish`

**Comment by soloturn** [comment]
this should work now, isn't it?
