### ISSUE TITLE
Illegal character in file name stops rip

### ISSUE THREAD

**Issue by Klutronic** [ripmeapp2/ripme#75]
* Ripme version:
* 2.1.1-3-536339dd
* Java version: 
* Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
* Operating system: 
* Microsoft Windows [Version 10.0.22000.556]

* Exact URL you were trying to rip when the problem occurred:
* **
![Issue](https://user-images.githubusercontent.com/11844408/158414775-fc4a345c-6a59-4ac1-bb54-3e02bfa214f1.png)
NSFW: https://www.reddit.com/user/Louise_fabs
* Please include any additional information about how to reproduce the problem:
* I am running this from the GUI

## Expected Behavior
Rips the user
Detail the expected behavior here.
Should rip the user even if there are illegal characters in the file name
## Actual Behavior
I am getting an error about an illegal character and the rip stops claiming completion.

This is NOT a problem in 2.0.4-13-03e32cb7 and works fine.

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
Error:
Illegal char <?> at index 79: E:\RipMe\rips\reddit_user_Louise_fabs/te7m00-tm2wmdhmxen81-Do you like my feet ?-.mp4

**Comment by soloturn** [comment]
would you please have a stack trace in the log, or the exact url where this happens?

**Comment by Klutronic** [comment]
The exact URL is https://www.reddit.com/user/Louise_fabs

**Comment by madhatr** [comment]
https://www.reddit.com/r/gonewild/comments/n9ik5t/swipe_for_a_surprise_we_both_know_what_the/  Here is one as well.  

I think it has to do with the Emoji in the title or maybe the emoji right beside the ),  here is the string causing the issue. It's the title of the post.

Swipe (f)or a surprise (we both know what the surprise is 😉)

**Comment by madhatr** [comment]
https://www.reddit.com/r/gonewild/comments/n9ik5t/swipe_for_a_surprise_we_both_know_what_the/

So for the URL have with this same issue it seems some invisible character is there?  I can't see it so I don't know what's going on. It may be some weird glitch with the emoji

Swipe (f)or a surprise (we both know what the surprise is 😉)

> 16:02:16.837 [Thread-52] ERROR com.rarchives.ripme.ripper.AbstractRipper - InvalidPathException:
java.nio.file.InvalidPathException: Trailing char < > at index 102: D:\github desktop\ripme\rips\reddit_post_n9ik5t\Swipe for a surprise we both know what the surprise is
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
        at java.nio.file.Path.of(Unknown Source) ~[?:?]
        at java.nio.file.Paths.get(Unknown Source) ~[?:?]
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:372) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:343) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:358) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:362) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:376) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleGallery(RedditRipper.java:456) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:218) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) ~[main/:?]
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:91) ~[main/:?]
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:626) [main/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
16:02:16.838 [Thread-52] DEBUG com.rarchives.ripme.ripper.AbstractRipper - Waiting for threads to finish
16:02:16.839 [Thread-52] INFO  com.rarchives.ripme.ripper.AbstractRipper -    Rip completed!
16:02:16.839 [Thread-52] INFO  com.rarchives.ripme.ripper.AbstractRipper - Deleting empty directory D:\github desktop\ripme\rips\reddit_post_n9ik5t

**Comment by soloturn** [comment]
@madhatr i removed this method call, and the method Utils.removeCWD as it was only used to print a log statement.

**Comment by madhatr** [comment]
https://www.reddit.com/r/gonewild/comments/n9ik5t/swipe_for_a_surprise_we_both_know_what_the/
![image](https://user-images.githubusercontent.com/14855242/162953019-b5d41c1b-40c9-40a4-915f-3a0ef058bb10.png)

> [+] Creating directory: E:\RipMe\rips\reddit_post_n9ik5t\Swipe for a surprise we both know what the surprise is 
Writing https://preview.redd.it/qo576225idy61.jpg?width=3020&format=pjpg&auto=webp&s=6308a64a7d1eef063a4d2053abe0e36270a9ca9d to file
Got exception while running ripper:
java.nio.file.InvalidPathException: Trailing char < > at index 87: E:\RipMe\rips\reddit_post_n9ik5t\Swipe for a surprise we both know what the surprise is \n9ik5t-01-qo576225idy61.jpg
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:172) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.io.File.toPath(File.java:2387) ~[?:?]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:353) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:357) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:361) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:375) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleGallery(RedditRipper.java:456) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:218) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:91) ~[ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:619) [ripme-2.1.1-4-5c9c13ab.jar:2.1.1-4-5c9c13ab]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Waiting for threads to finish
   Rip completed!

**Comment by madhatr** [comment]
Here is another URL that does it.   The title also contains emoji
"Can I be your a[f]ternoon snack? 👉🏻👈🏻"
https://www.reddit.com/r/gonewild/comments/u2zozx/can_i_be_your_afternoon_snack/

**Comment by soloturn** [comment]
thanks for the exception, there was no check if the name is good enough at AbstractRipper.java:353. can you try again?

**Comment by madhatr** [comment]
What's the collaborative chat room URL, I was in a few day ago but now can't find it anymore.

"Can I be your a[f]ternoon snack? 👉🏻👈🏻"
https://www.reddit.com/r/gonewild/comments/u2zozx/can_i_be_your_afternoon_snack/

Same issue for both above URL I found.

![image](https://user-images.githubusercontent.com/14855242/163583080-520f0f78-dec7-4730-90bd-17b1b81084ea.png)

> Downloading https://preview.redd.it/4pfxnpe4xct81.jpg?width=2316&format=pjpg&auto=webp&s=60e89f1ca7e5bd1e79289fd524708796b99c2221 to E:\RipMe\rips\reddit_post_u2zozx\Can I be your afternoon snack \u2zozx-02-4pfxnpe4xct81.jpg
[+] Creating directory: E:\RipMe\rips\reddit_post_u2zozx\Can I be your afternoon snack 
Writing https://preview.redd.it/4pfxnpe4xct81.jpg?width=2316&format=pjpg&auto=webp&s=60e89f1ca7e5bd1e79289fd524708796b99c2221 to file
Got exception while running ripper:
java.nio.file.InvalidPathException: Trailing char < > at index 62: E:\RipMe\rips\reddit_post_u2zozx\Can I be your afternoon snack \u2zozx-02-4pfxnpe4xct81.jpg
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:172) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.io.File.toPath(File.java:2387) ~[?:?]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:354) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:358) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:362) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:376) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleGallery(RedditRipper.java:456) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:218) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:91) ~[ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:620) [ripme-2.1.1-12-4be9ebae.jar:2.1.1-12-4be9ebae]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Waiting for threads to finish
   Rip completed!

**Comment by soloturn** [comment]
ok, another try, chat is on the main page, gitter.

**Comment by madhatr** [comment]
Both URL are confirmed working now.     Though an old issue I brought up before looks like it still remains.

I had to delete my history files as it though I had already downloaded the pictures when I had not due to the error.  

So it must log to history before confirming downloaded file was created successfully?

**Comment by soloturn** [comment]
lets open a different issue for the url history. not sure when to save what. on one hand it is there to prevent putting urls twice, on the other hand it seems to be there to remember for longer.
