### ISSUE TITLE
Illegal char, related #75

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#82]
I received this error from this user on reddit. I'll try to find the exact URL.

Illegal char <?> at index 116: E:\RipMe\rips\reddit_user_CosmicStarlight/qphh7n-lw0ykjgngey71-Anyone else loving the new Animal Crossing 2.0 update? &lt;3-.mp4

![image](https://user-images.githubusercontent.com/14855242/163686538-966ff842-e9de-4d14-b7b6-56942f9de2b5.png)

> Got exception while running ripper:
java.nio.file.InvalidPathException: Illegal char <?> at index 116: E:\RipMe\rips\reddit_user_CosmicStarlight/qphh7n-lw0ykjgngey71-Anyone else loving the new Animal Crossing 2.0 update? &lt;3-.mp4
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:417) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:221) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:91) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Waiting for threads to finish

#75

**Comment by madhatr** [comment]
> Status code: 200
url: https://v.redd.it/t0kznyk4v8p81/DASH_720.mp4 file: E:\RipMe\rips\reddit_user_LaPetiteX/tlvpth-t0kznyk4v8p81-Would you like me to be your nurse?-.mp4
Got exception while running ripper:
java.nio.file.InvalidPathException: Illegal char <?> at index 91: E:\RipMe\rips\reddit_user_LaPetiteX/tlvpth-t0kznyk4v8p81-Would you like me to be your nurse?-.mp4
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:417) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:221) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:91) ~[ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.1-15-9a683538.jar:2.1.1-15-9a683538]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Waiting for threads to finish
   Rip completed!

**Comment by soloturn** [comment]
there are quite a number of other "Path.get" in the code which may fail in a similar fashion. as well, for windows and others, the filename should be shortened in such a situation. below some occurrences which would need a check.

```
> git grep -i paths.get
...
src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java:                || Utils.fuzzyExists(Paths.get(saveAs.getParent()), saveAs.getName()) && getFileExtFromMIME
src/main/java/com/rarchives/ripme/ripper/rippers/EHentaiRipper.java:                    addURLToDownload(new URL(imgsrc), Paths.get(savePath));
src/main/java/com/rarchives/ripme/ripper/rippers/FivehundredpxRipper.java:        Path saveAs = Paths.get(getWorkingDir() + prefix + ".jpg");
src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java:            saveFileAs = Paths.get(
src/main/java/com/rarchives/ripme/ripper/rippers/PahealRipper.java:            Path outFile = Paths.get(workingDir
src/main/java/com/rarchives/ripme/ui/MainWindow.java:        Path historyFile = Paths.get(Utils.getConfigDir() + File.separator + "history.json");
src/main/java/com/rarchives/ripme/utils/Utils.java:        return saveAs.relativize(Paths.get(".").toAbsolutePath()).toString();
src/main/java/com/rarchives/ripme/utils/Utils.java:                myPath = Paths.get(uri).getParent();
src/main/java/com/rarchives/ripme/utils/Utils.java:        return Paths.get(sanitizeSaveAs(pathToSanitize));
src/main/java/com/rarchives/ripme/utils/Utils.java:        return Paths.get(fullPath);
src/test/java/com/rarchives/ripme/tst/UtilsTest.java:        Assertions.assertEquals(Paths.get(
```
