### ISSUE TITLE
Window changed size to larger than entire desktop space.

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#90]
As the title states.   (horizontally, not vertically)

Version ripme-2.1.2-14-827cc133
Win 11

![image](https://user-images.githubusercontent.com/14855242/168096408-916c8ea6-29eb-455f-9cfe-45864baa227e.png)

Here is part of the log.

> [!] Error creating save file path for description 'https://www.reddit.com/user/HungrHrts/':
java.nio.file.NoSuchFileException: E__RipMe_rips_reddit_user_HungrHrts\u23tx2__let's get shredded!_.html
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.saveText(RedditRipper.java:297) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:123) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://i.redd.it/nkeo6wrm6ts81.jpg
Found single URL: https://i.redd.it/nkeo6wrm6ts81.jpg
Checking https://i.imgur.com/j164d4N.gifv
Checking https://i.imgur.com/AxcQWjQ.gifv
Checking https://i.redd.it/nv7gg4c6der81.jpg
Found single URL: https://i.redd.it/nv7gg4c6der81.jpg
Checking https://i.imgur.com/CBLCZPz.gifv
Checking https://i.redd.it/ifo11x7ffgq81.jpg
Found single URL: https://i.redd.it/ifo11x7ffgq81.jpg
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking https://i.redd.it/ctn0c1eqynl81.jpg
Found single URL: https://i.redd.it/ctn0c1eqynl81.jpg
Checking https://i.redd.it/q66zpl8odhk81.jpg
Found single URL: https://i.redd.it/q66zpl8odhk81.jpg
Checking https://i.redd.it/ikqv9io3os981.jpg
Found single URL: https://i.redd.it/ikqv9io3os981.jpg
Checking https://www.youtube.com/watch?v=BK30r_SIZ-g
[!] Unable to rip URL: https://www.youtube.com/watch?v=BK30r_SIZ-g
Checking https://i.redd.it/b77vsyl331881.jpg
Found single URL: https://i.redd.it/b77vsyl331881.jpg
Checking https://i.redd.it/6xoqcgjps0781.jpg
Found single URL: https://i.redd.it/6xoqcgjps0781.jpg
Checking https://i.redd.it/fqiav4dhb1681.jpg
Found single URL: https://i.redd.it/fqiav4dhb1681.jpg
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking https://i.redd.it/rb47xjmjudl71.jpg
Found single URL: https://i.redd.it/rb47xjmjudl71.jpg
Checking https://i.redd.it/fa5ucc7y45l71.jpg
Found single URL: https://i.redd.it/fa5ucc7y45l71.jpg
Checking https://i.redd.it/mukic41wub571.jpg
Found single URL: https://i.redd.it/mukic41wub571.jpg
Checking https://i.redd.it/hvnej05nyo371.jpg
Found single URL: https://i.redd.it/hvnej05nyo371.jpg
Checking https://i.redd.it/fmd84grmmx271.jpg
Found single URL: https://i.redd.it/fmd84grmmx271.jpg
Checking https://i.redd.it/369guazg73651.jpg
Found single URL: https://i.redd.it/369guazg73651.jpg
Checking https://i.redd.it/69psvban38p41.gif
Found single URL: https://i.redd.it/69psvban38p41.gif
Checking https://i.redd.it/yjfk8b5uni631.jpg
Found single URL: https://i.redd.it/yjfk8b5uni631.jpg
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking https://imgur.com/0cKJiMr
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
[!] Error creating save file path for description 'https://www.reddit.com/user/HungrHrts/':
java.nio.file.NoSuchFileException: E__RipMe_rips_reddit_user_HungrHrts\axag4a_Never Underestimate the Power of Using Your Words! [Anal Success Story].html
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.saveText(RedditRipper.java:297) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:123) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://optimalnutritioncanada.files.wordpress.com/2011/10/pam.gif
Found single URL: https://optimalnutritioncanada.files.wordpress.com/2011/10/pam.gif
Checking https://gfycat.com/RegalEdibleComet
Fetching gfycat page https://gfycat.com/RegalEdibleComet
Retrieving https://gfycat.com/RegalEdibleComet
Trying to load cookies from config for gfycat.com
Exception while retrieving gfycat page:
java.io.IOException: null
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:158) ~[ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:73) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:406) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:224) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
[!] Error creating save file path for description 'https://www.reddit.com/user/HungrHrts/':
java.nio.file.NoSuchFileException: E__RipMe_rips_reddit_user_HungrHrts\anry43_I Hate Food.html
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.saveText(RedditRipper.java:297) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:123) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://imgur.com/a/Se8CFgX
Fetching imgur album at https://imgur.com/a/Se8CFgX
    Retrieving https://imgur.com/a/Se8CFgX/all
{"data":{"id":"Se8CFgX","title":null,"description":null,"datetime":1547410295,"cover":"cho1rWv","cover_edited":null,"cover_width":1920,"cover_height":1080,"account_url":null,"account_id":null,"privacy":"hidden","layout":"blog","views":5979,"link":"https:\/\/imgur.com\/a\/Se8CFgX","favorite":false,"nsfw":true,"section":"gonewild","images_count":1,"in_gallery":false,"is_ad":false,"include_album_ads":false,"is_album":true,"images":[{"id":"cho1rWv","title":null,"description":null,"datetime":1547410292,"type":"image\/jpeg","animated":false,"width":1920,"height":1080,"size":409406,"views":16555,"bandwidth":6777716330,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":null,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"0","in_gallery":false,"link":"https:\/\/i.imgur.com\/cho1rWv.jpg"}],"ad_config":{"safeFlags":["not_in_gallery","share"],"highRiskFlags":[],"unsafeFlags":["sixth_mod_unsafe","onsfw_mod_unsafe","nsfw"],"wallUnsafeFlags":["onsfw_mod_unsafe_wall","nsfw"],"showsAds":false,"showAdLevel":0}},"success":true,"status":200}
Got imgur image: https://i.imgur.com/cho1rWv.jpg
Checking https://media.tenor.com/images/3481b798e8ceb0a0f8e4b1a64aab0e72/tenor.gif
Found single URL: https://media.tenor.com/images/3481b798e8ceb0a0f8e4b1a64aab0e72/tenor.gif
Checking https://gfycat.com/WelllitCheeryHake
Fetching gfycat page https://gfycat.com/WelllitCheeryHake
Retrieving https://gfycat.com/WelllitCheeryHake
Trying to load cookies from config for gfycat.com
Exception while retrieving gfycat page:
java.io.IOException: null
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:158) ~[ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:73) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:406) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:224) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://i.imgur.com/CPvW8Qg.jpg
Found single URL: https://i.imgur.com/CPvW8Qg.jpg
Checking https://i.imgur.com/BVnZbC2.jpg
Found single URL: https://i.imgur.com/BVnZbC2.jpg
Checking https://imgur.com/vo0cf14
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Checking https://i.imgur.com/IhFHoFl.jpg
Found single URL: https://i.imgur.com/IhFHoFl.jpg
Checking https://gfycat.com/gifs/detail/mixedfarawaylacewing
Fetching gfycat page https://gfycat.com/gifs/detail/mixedfarawaylacewing
Retrieving https://gfycat.com/gifs/detail/mixedfarawaylacewing
Trying to load cookies from config for gfycat.com
Exception while retrieving gfycat page:
java.io.IOException: null
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:158) ~[ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:73) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:406) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:224) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://gfycat.com/MixedFarawayLacewing
Fetching gfycat page https://gfycat.com/MixedFarawayLacewing
Retrieving https://gfycat.com/MixedFarawayLacewing
Trying to load cookies from config for gfycat.com
Exception while retrieving gfycat page:
java.io.IOException: null
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:158) ~[ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:73) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:406) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:224) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:116) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:90) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:627) [ripme-2.1.2-14-827cc133.jar:2.1.2-14-827cc133]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Checking https://imgur.com/a/Wqf0YF4
Fetching imgur album at https://imgur.com/a/Wqf0YF4
    Retrieving https://imgur.com/a/Wqf0YF4/all
{"data":{"id":"Wqf0YF4","title":null,"description":null,"datetime":1537829640,"cover":"wnD6jLx","cover_edited":null,"cover_width":1354,"cover_height":759,"account_url":null,"account_id":null,"privacy":"hidden","layout":"blog","views":15767,"link":"https:\/\/imgur.com\/a\/Wqf0YF4","favorite":false,"nsfw":true,"section":"gonewild","images_count":3,"in_gallery":false,"is_ad":false,"include_album_ads":false,"is_album":true,"images":[{"id":"wnD6jLx","title":null,"description":null,"datetime":1537829633,"type":"image\/jpeg","animated":false,"width":1354,"height":759,"size":94969,"views":26983,"bandwidth":2562548527,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":null,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"1","in_gallery":false,"link":"https:\/\/i.imgur.com\/wnD6jLx.jpg?1"},{"id":"aJZ2hHG","title":null,"description":null,"datetime":1537829628,"type":"image\/jpeg","animated":false,"width":1355,"height":749,"size":89537,"views":20842,"bandwidth":1866130154,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":null,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"1","in_gallery":false,"link":"https:\/\/i.imgur.com\/aJZ2hHG.jpg?1"},{"id":"BWn8eUJ","title":null,"description":null,"datetime":1537829624,"type":"image\/jpeg","animated":false,"width":1355,"height":757,"size":96362,"views":19371,"bandwidth":1866628302,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":null,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"1","in_gallery":false,"link":"https:\/\/i.imgur.com\/BWn8eUJ.jpg?1"}],"ad_config":{"safeFlags":["not_in_gallery","share"],"highRiskFlags":[],"unsafeFlags":["sixth_mod_unsafe","onsfw_mod_unsafe","nsfw"],"wallUnsafeFlags":["onsfw_mod_unsafe_wall","nsfw"],"showsAds":false,"showAdLevel":0}},"success":true,"status":200}
Got imgur image: https://i.imgur.com/wnD6jLx.jpg?1
Got imgur image: https://i.imgur.com/aJZ2hHG.jpg?1
Got imgur image: https://i.imgur.com/BWn8eUJ.jpg?1
Waiting for threads to finish
   Rip completed!

**Comment by madhatr** [comment]
Also it continued to rip 88 more url's.  The gui showed the last rip as "Rip complete, saved to E:\RipMe\rips\reddit_user_HungrHrts" yet there was 88 newer folders in the rip folder.
