### ISSUE TITLE
Twitter giving java.lang.IllegalArgumentException: 'other'

### ISSUE THREAD

**Issue by tanja84dk** [ripmeapp2/ripme#91]
* Ripme version: 2.1.2-3-ea90b172

* Java version: openjdk 19-ea 2022-09-20
OpenJDK Runtime Environment (build 19-ea+19-1283)
OpenJDK 64-Bit Server VM (build 19-ea+19-1283, mixed mode, sharing)

* Operating system: Ubuntu 20.04.4 LTS and Oracle Linux 8

tested on docker image openjdk:19 ( I believe that is Oracle Linux 8 ) and bare metal server which are Ubuntu 20.04.4 LTS Server

* Exact URL you were trying to rip when the problem occurred: https://twitter.com/tanja84dk
* Please include any additional information about how to reproduce the problem:
Ran following command because I’m used to it working on the original RipMe:
“””
java -jar ripme-2.1.2-3-ea90b172.jar -u https://twitter.com/tanja84dk
“””

## Expected Behavior

Expected would be that it would download my content from my profile

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

“””
07:38:20.852 [main] ERROR com.rarchives.ripme.App - [!] Error while ripping URL https://twitter.com/tanja84dk
java.lang.IllegalArgumentException: 'other' is different type of Path
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:398) ~[?:?]
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:43) ~[?:?]
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:325) ~[ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.ripper.AbstractJSONRipper.setWorkingDir(AbstractJSONRipper.java:294) ~[ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:187) ~[ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.App.rip(App.java:99) ~[ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.App.ripURL(App.java:293) [ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.App.handleArguments(App.java:276) [ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
        at com.rarchives.ripme.App.main(App.java:75) [ripme-2.1.2-3-ea90b172.jar:2.1.2-3-ea90b172]
“””

**Comment by Mojavve** [comment]
Same issue here.  Twitter just doesn't work at this point.

**Comment by tanja84dk** [comment]
Yeah and the funny thing is that it works fine with the original version still so I guess its messed up by this repos maintainer unfortunally and not from twitters side

**Comment by soloturn** [comment]
really, you see the difference?
